//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeskUMP.Service_References.Salesforce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandeskUMP.Service_References.Salesforce.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, CaseNumber, Severity__c, CreatedDate, ClosedDate, Product_Line__c, Category__c, AccountId, Account.Name, Account.SAP_Customer_Number__c,Account.Total_Entitlement_Points__c
        ///  FROM Case
        /// WHERE Product_Line__c LIKE &apos;Systems Lifecycle%&apos; .
        /// </summary>
        internal static string AllCases {
            get {
                return ResourceManager.GetString("AllCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, CaseNumber, Severity__c, ClearQuestID__c, CreatedDate, ClosedDate, Product_Line__c, Category__c, Status, AccountId, Account.Name, Account.SAP_Customer_Number__c, Account.Total_Entitlement_Points__c&quot;
        ///  FROM Case
        /// WHERE Product_Line__c LIKE &apos;Systems Lifecycle%&apos; 
        ///   AND LastModifiedDate &gt; &lt;%lastUpdate%&gt;.
        /// </summary>
        internal static string AllCasesWithDefects {
            get {
                return ResourceManager.GetString("AllCasesWithDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, CaseNumber, Status, Severity__c, CreatedDate, ClosedDate, Product_Line__c, Category__c, AccountId, Account.Name, Account.SAP_Customer_Number__c,Account.Total_Entitlement_Points__c,
        ///      (SELECT CommentBody, CreatedById, CreatedDate, ParentId, IsPublished
        ///         FROM CaseComments)
        ///  FROM Case
        /// WHERE Product_Line__c LIKE &apos;Systems Lifecycle%&apos; 
        ///   AND RecordType.Name = &apos;Customer Service&apos; 
        ///   AND CreatedDate &gt; &lt;%lastUpdate%&gt;.
        /// </summary>
        internal static string CasesWithComments {
            get {
                return ResourceManager.GetString("CasesWithComments", resourceCulture);
            }
        }
    }
}
